#!/bin/bash

# ###############################################################
# Activates prodiguer-shell
# ###############################################################

# Import environment vars.
source $HOME/.prodiguer_server

# CV server related commands.
alias prodiguer-cv-git-push=$PRODIGUER_HOME/bash/cv/git_push.sh

# DB server related commands.
alias prodiguer-db-pgres-backup=$PRODIGUER_HOME/bash/db/pgres_backup.sh
alias prodiguer-db-pgres-install=$PRODIGUER_HOME/bash/db/pgres_install.sh
alias prodiguer-db-pgres-migrate=$PRODIGUER_HOME/bash/db/pgres_migrate.sh
alias prodiguer-db-pgres-reset=$PRODIGUER_HOME/bash/db/pgres_reset_db.sh
alias prodiguer-db-pgres-reset-cv-table=$PRODIGUER_HOME/bash/db/pgres_reset_cv_table.sh
alias prodiguer-db-pgres-reset-email-table=$PRODIGUER_HOME/bash/db/pgres_reset_email_table.sh
alias prodiguer-db-pgres-reset-message-table=$PRODIGUER_HOME/bash/db/pgres_reset_message_table.sh
alias prodiguer-db-pgres-reset-environment-metric-table=$PRODIGUER_HOME/bash/db/pgres_reset_environment_metric_table.sh
alias prodiguer-db-pgres-restore=$PRODIGUER_HOME/bash/db/pgres_restore.sh
alias prodiguer-db-pgres-uninstall=$PRODIGUER_HOME/bash/db/pgres_uninstall.sh

# MQ server related commands.
alias prodiguer-mq-configure-rabbitmq=$PRODIGUER_HOME/bash/mq/configure_rabbitmq.sh
alias prodiguer-mq-consume=$PRODIGUER_HOME/bash/mq/run_agent.sh
alias prodiguer-mq-daemons-init=$PRODIGUER_HOME/bash/mq/daemons_init.sh
alias prodiguer-mq-daemons-kill=$PRODIGUER_HOME/bash/mq/daemons_kill.sh
alias prodiguer-mq-daemons-reset-logs=$PRODIGUER_HOME/bash/mq/daemons_reset_logs.sh
alias prodiguer-mq-daemons-status=$PRODIGUER_HOME/bash/mq/daemons_status.sh
alias prodiguer-mq-daemons-update-config=$PRODIGUER_HOME/bash/mq/daemons_update_config.sh
alias prodiguer-mq-daemons-update-config-for-debug=$PRODIGUER_HOME/bash/mq/daemons_update_config_for_debug.sh
alias prodiguer-mq-produce=$PRODIGUER_HOME/bash/mq/run_agent.sh
alias prodiguer-mq-purge=$PRODIGUER_HOME/bash/mq/purge_queues.sh
alias prodiguer-mq-purge-debug-queues=$PRODIGUER_HOME/bash/mq/purge_queues_debug.sh

# OS (operating system) related commands.
alias prodiguer-os-setup=$PRODIGUER_HOME/bash/os/setup.sh

# WEB server related commands.
alias prodiguer-web-api=$PRODIGUER_HOME/bash/web/run_web_service.sh
alias prodiguer-web-daemons-init=$PRODIGUER_HOME/bash/web/daemons_init.sh
alias prodiguer-web-daemons-kill=$PRODIGUER_HOME/bash/web/daemons_kill.sh
alias prodiguer-web-daemons-reset-logs=$PRODIGUER_HOME/bash/web/daemons_reset_logs.sh
alias prodiguer-web-daemons-status=$PRODIGUER_HOME/bash/web/daemons_status.sh
alias prodiguer-web-daemons-update-config=$PRODIGUER_HOME/bash/web/daemons_update_config.sh
alias prodiguer-web-daemons-update-config-for-debug=$PRODIGUER_HOME/bash/web/daemons_update_config_for_debug.sh


# Supported command types.
declare -a PRODIGUER_SHELL_COMMAND_TYPES=(
	stack
	utests
)

# Supported commands.
declare -a PRODIGUER_SHELL_COMMANDS=(
	# Stack management.
	stack-install
	stack-update
	stack-update-config
	stack-update-shell
	stack-update-repo
	stack-update-repos
	stack-update-venv
	stack-update-venvs
	stack-update-source
	stack-upgrade-venvs
	stack-uninstall
	stack-uninstall-repo
	stack-config-commit
	stack-config-encrypt
	stack-config-decrypt
	# Tests.
	tests
)

# Set path to exec.sh.
PRODIGUER_SHELL_EXEC="$( dirname "${BASH_SOURCE[0]}" )"/bash/exec.sh

# Create default alias.
alias prodiguer=$PRODIGUER_SHELL_EXEC

# Create command aliases.
for PRODIGUER_SHELL_COMMAND in "${PRODIGUER_SHELL_COMMANDS[@]}"
do
	alias prodiguer-$PRODIGUER_SHELL_COMMAND=$PRODIGUER_SHELL_EXEC" "$PRODIGUER_SHELL_COMMAND
done

# Composite commands.
alias prodiguer-db-reset='prodiguer-cv-git-pull && prodiguer-db-pgres-reset'

# Unset helper vars.
unset PRODIGUER_SHELL_EXEC
unset PRODIGUER_SHELL_COMMAND
unset PRODIGUER_SHELL_COMMANDS
unset PRODIGUER_SHELL_COMMAND_TYPE
unset PRODIGUER_SHELL_COMMAND_TYPES
