#!/bin/bash

# ###############################################################
# Activates prodiguer-shell
# ###############################################################

# Import environment vars.
source $HOME/.prodiguer

# CV server related commands.
alias prodiguer-cv-git-push=$PRODIGUER_HOME/bash/cv/git_push.sh

# DB server related commands.
alias prodiguer-db-pgres-backup=$PRODIGUER_HOME/bash/db/pgres_backup.sh
alias prodiguer-db-pgres-install=$PRODIGUER_HOME/bash/db/pgres_install.sh
alias prodiguer-db-pgres-migrate=$PRODIGUER_HOME/bash/db/pgres_migrate.sh
alias prodiguer-db-pgres-reset=$PRODIGUER_HOME/bash/db/pgres_reset_db.sh
alias prodiguer-db-pgres-reset-cv-table=$PRODIGUER_HOME/bash/db/pgres_reset_cv_table.sh
alias prodiguer-db-pgres-reset-environment-metric-table=$PRODIGUER_HOME/bash/db/pgres_reset_environment_metric_table.sh
alias prodiguer-db-pgres-reset-message-email-table=$PRODIGUER_HOME/bash/db/pgres_reset_message_email_table.sh
alias prodiguer-db-pgres-reset-message-table=$PRODIGUER_HOME/bash/db/pgres_reset_message_table.sh
alias prodiguer-db-pgres-restore=$PRODIGUER_HOME/bash/db/pgres_restore.sh
alias prodiguer-db-pgres-uninstall=$PRODIGUER_HOME/bash/db/pgres_uninstall.sh

# MQ server related commands.
alias prodiguer-mq-run-agent=$PRODIGUER_HOME/bash/mq/run_agent.sh
alias prodiguer-mq-daemons-ctl=$PRODIGUER_HOME/bash/mq/daemons_ctl.sh
alias prodiguer-mq-daemons-init=$PRODIGUER_HOME/bash/mq/daemons_init.sh
alias prodiguer-mq-daemons-kill=$PRODIGUER_HOME/bash/mq/daemons_kill.sh
alias prodiguer-mq-daemons-reset-logs=$PRODIGUER_HOME/bash/mq/daemons_reset_logs.sh
alias prodiguer-mq-daemons-status=$PRODIGUER_HOME/bash/mq/daemons_status.sh
alias prodiguer-mq-daemons-update-config=$PRODIGUER_HOME/bash/mq/daemons_update_config.sh
alias prodiguer-mq-daemons-update-config-for-debug=$PRODIGUER_HOME/bash/mq/daemons_update_config_for_debug.sh
alias prodiguer-mq-import-broker-definitions=$PRODIGUER_HOME/bash/mq/import_broker_definitions.sh
alias prodiguer-mq-purge-queues=$PRODIGUER_HOME/bash/mq/purge_queues.sh
alias prodiguer-mq-purge-queues-live=$PRODIGUER_HOME/bash/mq/purge_queues_live.sh
alias prodiguer-mq-purge-queues-debug=$PRODIGUER_HOME/bash/mq/purge_queues_debug.sh

# Stack management related commands.
alias prodiguer-stack-install=$PRODIGUER_HOME/bash/stack/install.sh
alias prodiguer-stack-uninstall=$PRODIGUER_HOME/bash/stack/uninstall.sh
alias prodiguer-stack-update=$PRODIGUER_HOME/bash/stack/update.sh
alias prodiguer-stack-update-config=$PRODIGUER_HOME/bash/stack/update_config.sh
alias prodiguer-stack-update-environment-vars=$PRODIGUER_HOME/bash/stack/update_environment_vars.sh
alias prodiguer-stack-update-repos=$PRODIGUER_HOME/bash/stack/update_repos.sh
alias prodiguer-stack-update-shell=$PRODIGUER_HOME/bash/stack/update_shell.sh
alias prodiguer-stack-upgrade-venv=$PRODIGUER_HOME/bash/stack/upgrade_venv.sh
alias prodiguer-stack-upgrade-venvs=$PRODIGUER_HOME/bash/stack/upgrade_venvs.sh

# Tests related commands.
alias prodiguer-tests-run=$PRODIGUER_HOME/bash/tests/run.sh
alias prodiguer-tests-noop=$PRODIGUER_HOME/bash/tests/noop.sh

# WEB server related commands.
alias prodiguer-web-daemons-ctl=$PRODIGUER_HOME/bash/web/daemons_ctl.sh
alias prodiguer-web-daemons-init=$PRODIGUER_HOME/bash/web/daemons_init.sh
alias prodiguer-web-daemons-kill=$PRODIGUER_HOME/bash/web/daemons_kill.sh
alias prodiguer-web-daemons-reset-logs=$PRODIGUER_HOME/bash/web/daemons_reset_logs.sh
alias prodiguer-web-daemons-status=$PRODIGUER_HOME/bash/web/daemons_status.sh
alias prodiguer-web-daemons-update-config=$PRODIGUER_HOME/bash/web/daemons_update_config.sh
alias prodiguer-web-daemons-update-config-for-debug=$PRODIGUER_HOME/bash/web/daemons_update_config_for_debug.sh
alias prodiguer-web-send-monitoring-event=$PRODIGUER_HOME/bash/web/send_monitoring_event.sh
alias prodiguer-web-service=$PRODIGUER_HOME/bash/web/run_web_service.sh

# Composite commands.
alias prodiguer-daemons-init='prodiguer-web-daemons-init && prodiguer-mq-daemons-init'
alias prodiguer-daemons-kill='prodiguer-mq-daemons-kill && prodiguer-web-daemons-kill'
alias prodiguer-db-reset='prodiguer-cv-git-pull && prodiguer-db-pgres-reset'
alias prodiguer-stack-update-source='prodiguer-stack-update-shell && prodiguer-stack-update-repos'

# Ensure target scripts are executable.
chmod a+x $PRODIGUER_HOME/bash/cv/*.sh
chmod a+x $PRODIGUER_HOME/bash/db/*.sh
chmod a+x $PRODIGUER_HOME/bash/mq/*.sh
chmod a+x $PRODIGUER_HOME/bash/os/*.sh
chmod a+x $PRODIGUER_HOME/bash/stack/*.sh
chmod a+x $PRODIGUER_HOME/bash/tests/*.sh
chmod a+x $PRODIGUER_HOME/bash/web/*.sh
