#!/bin/bash

# ###############################################################
# Activates hermes-shell
# ###############################################################

# Import environment vars.
source $HOME/.hermes

# CV server related commands.
alias hermes-cv-git-pull=$HERMES_HOME/bash/cv/git_pull.sh
alias hermes-cv-git-push=$HERMES_HOME/bash/cv/git_push.sh
alias hermes-cv-seed-pyessv=$HERMES_HOME/bash/cv/seed_pyessv.sh

# PostgreSQL DB server related commands.
alias hermes-db-pgres-backup=$HERMES_HOME/bash/db/pgres_backup.sh
alias hermes-db-pgres-backup=$HERMES_HOME/bash/db/pgres_backup.sh
alias hermes-db-pgres-create-test-db=$HERMES_HOME/bash/db/pgres_create_test_db.sh
alias hermes-db-pgres-create-users='$HERMES_HOME/bash/db/pgres_create_db_users.sh && $HERMES_HOME/bash/db/pgres_grant_permissions.sh'
alias hermes-db-pgres-delete-simulation=$HERMES_HOME/bash/db/pgres_delete_simulation.sh
alias hermes-db-pgres-grant-permissions=$HERMES_HOME/bash/db/pgres_grant_permissions.sh
alias hermes-db-pgres-migrate=$HERMES_HOME/bash/db/pgres_migrate.sh
alias hermes-db-pgres-performance-tests=$HERMES_HOME/bash/db/pgres_performance_tests.sh
alias hermes-db-pgres-rectify-phase-1=$HERMES_HOME/bash/db/pgres_rectify_phase_1.sh
alias hermes-db-pgres-rectify-phase-2=$HERMES_HOME/bash/db/pgres_rectify_phase_2.sh
alias hermes-db-pgres-reset=$HERMES_HOME/bash/db/pgres_reset_db.sh
alias hermes-db-pgres-truncate-conso=$HERMES_HOME/bash/db/pgres_truncate_conso.sh
alias hermes-db-pgres-truncate-cv=$HERMES_HOME/bash/db/pgres_truncate_cv.sh
alias hermes-db-pgres-truncate-monitoring=$HERMES_HOME/bash/db/pgres_truncate_monitoring.sh
alias hermes-db-pgres-truncate-mq-emails=$HERMES_HOME/bash/db/pgres_truncate_mq_emails.sh
alias hermes-db-pgres-truncate-mq-messages=$HERMES_HOME/bash/db/pgres_truncate_mq_messages.sh
alias hermes-db-pgres-restore=$HERMES_HOME/bash/db/pgres_restore.sh
alias hermes-db-pgres-show-object-sizes=$HERMES_HOME/bash/db/pgres_show_object_sizes.sh
alias hermes-db-pgres-install=$HERMES_HOME/bash/db/pgres_install.sh
alias hermes-db-pgres-uninstall=$HERMES_HOME/bash/db/pgres_uninstall.sh
alias hermes-db-pgres-update-conso=$HERMES_HOME/bash/db/pgres_update_conso.sh
alias hermes-db-pgres-vacuum=$HERMES_HOME/bash/db/pgres_vacuum.sh
alias hermes-db-pgres-vacuum-full=$HERMES_HOME/bash/db/pgres_vacuum_full.sh

# Mongo DB server related commands.
alias hermes-db-mongo-setup=$HERMES_HOME/bash/db/mongo_setup.sh

# MQ server related commands.
alias hermes-mq-run-agent=$HERMES_HOME/bash/mq/run_agent.sh
alias hermes-mq-daemons-ctl=$HERMES_HOME/bash/mq/daemons_ctl.sh
alias hermes-mq-daemons-init=$HERMES_HOME/bash/mq/daemons_init.sh
alias hermes-mq-daemons-kill=$HERMES_HOME/bash/mq/daemons_kill.sh
alias hermes-mq-daemons-kill-phase-1=$HERMES_HOME/bash/mq/daemons_kill_phase_1.sh
alias hermes-mq-daemons-kill-phase-2=$HERMES_HOME/bash/mq/daemons_kill_phase_2.sh
alias hermes-mq-daemons-reload=$HERMES_HOME/bash/mq/daemons_reload.sh
alias hermes-mq-daemons-reset-logs=$HERMES_HOME/bash/mq/daemons_reset_logs.sh
alias hermes-mq-daemons-status=$HERMES_HOME/bash/mq/daemons_status.sh
alias hermes-mq-daemons-update-config=$HERMES_HOME/bash/mq/daemons_update_config.sh
alias hermes-mq-import-broker-definitions=$HERMES_HOME/bash/mq/import_broker_definitions.sh
alias hermes-mq-purge-queues=$HERMES_HOME/bash/mq/purge_queues.sh
alias hermes-mq-purge-queues-live=$HERMES_HOME/bash/mq/purge_queues_live.sh
alias hermes-mq-purge-queues-debug=$HERMES_HOME/bash/mq/purge_queues_debug.sh

# Stack management related commands.
alias hermes-stack-install=$HERMES_HOME/bash/stack/install.sh
alias hermes-stack-install-python=$HERMES_HOME/bash/stack/install_python.sh
alias hermes-stack-install-venv=$HERMES_HOME/bash/stack/install_venv.sh
alias hermes-stack-install-environment-vars=$HERMES_HOME/bash/stack/install_environment_vars.sh

alias hermes-stack-uninstall=$HERMES_HOME/bash/stack/uninstall.sh

alias hermes-stack-update=$HERMES_HOME/bash/stack/update.sh
alias hermes-stack-update-config=$HERMES_HOME/bash/stack/update_config.sh
alias hermes-stack-update-environment-vars=$HERMES_HOME/bash/stack/update_environment_vars.sh
alias hermes-stack-update-repos=$HERMES_HOME/bash/stack/update_repos.sh
alias hermes-stack-update-shell=$HERMES_HOME/bash/stack/update_shell.sh
alias hermes-stack-update-venv=$HERMES_HOME/bash/stack/update_venv.sh

# Tests related commands.
alias hermes-tests-run=$HERMES_HOME/bash/tests/run.sh

# WEB server related commands.
alias hermes-web-daemons-ctl=$HERMES_HOME/bash/web/daemons_ctl.sh
alias hermes-web-daemons-init=$HERMES_HOME/bash/web/daemons_init.sh
alias hermes-web-daemons-kill=$HERMES_HOME/bash/web/daemons_kill.sh
alias hermes-web-daemons-reload=$HERMES_HOME/bash/web/daemons_reload.sh
alias hermes-web-daemons-reset-logs=$HERMES_HOME/bash/web/daemons_reset_logs.sh
alias hermes-web-daemons-status=$HERMES_HOME/bash/web/daemons_status.sh
alias hermes-web-daemons-update-config=$HERMES_HOME/bash/web/daemons_update_config.sh
alias hermes-web-test-monitoring-event=$HERMES_HOME/bash/web/test_monitoring_event.sh
alias hermes-web-service=$HERMES_HOME/bash/web/run_web_service.sh

# Composite commands.
alias hermes-daemons-init='hermes-web-daemons-init && hermes-mq-daemons-init'
alias hermes-daemons-kill='hermes-mq-daemons-kill && hermes-web-daemons-kill'
alias hermes-db-reset='hermes-cv-git-pull && hermes-db-pgres-reset'

alias hermes-stack-update-source='hermes-stack-update-shell && hermes-stack-update-repos && hermes-stack-update-config'

# Misc one off commands.
alias hermes-cv-seed-accounting-projects=$HERMES_HOME/bash/cv/seed_accounting_projects.sh
