#!/bin/bash

# ###############################################################
# Deactivates prodiguer-shell
# ###############################################################

unset HERMES_DIR_BASH
unset HERMES_DIR_BACKUPS
unset HERMES_DIR_CERTS
unset HERMES_DIR_CONFIG
unset HERMES_DIR_DAEMONS
unset HERMES_DIR_DATA
unset HERMES_DIR_JOBS
unset HERMES_DIR_LOGS
unset HERMES_DIR_PYTHON
unset HERMES_DIR_REPOS
unset HERMES_DIR_TEMPLATES
unset HERMES_DIR_SERVER
unset HERMES_DIR_SERVER_TESTS
unset HERMES_DIR_TMP
unset HERMES_DIR_VENV

unset HERMES_REPOS
unset HERMES_VENVS
unset HERMES_OPS_DIRS
