#!/bin/bash

# Initialise.
declare PRODIGUER_HOME=${PRODIGUER_HOME:="/opt/prodiguer"}
source $PRODIGUER_HOME/bash/init.sh

# Invoke action.
$PRODIGUER_ACTION $PRODIGUER_ACTION_ARG1 $PRODIGUER_ACTION_ARG2 $PRODIGUER_ACTION_ARG3 $PRODIGUER_ACTION_ARG4 $PRODIGUER_ACTION_ARG5

# End.
log_banner
exit 0
